### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by agarzon48** [AlvaroMartinFernandez/Domain-Generator#2]
La aplicación tiene un problema: cuando un dominio cumple las condiciones para aplicar el hack, el output lo repite sin combinaciones. Ejemplo:

````
[
  'thegreatjogger.com', 'thegreatjogger.net', 'thegreatjogger.es',
  'thegreatjogger.eu',  'thegreatracoon.com', 'thegreatracoon.net',
  'thegreatracoon.es',  'thegreatracoon.eu',  'thegreatpued.es',
  'thegreatpued.es',    'thegreatpued.es',    'thegreatpued.es',
  'thebigjogger.com',   'thebigjogger.net',   'thebigjogger.es',
  'thebigjogger.eu',    'thebigracoon.com',   'thebigracoon.net',
  'thebigracoon.es',    'thebigracoon.eu',    'thebigpued.es',
  'thebigpued.es',      'thebigpued.es',      'thebigpued.es',
  'ourgreatjogger.com', 'ourgreatjogger.net', 'ourgreatjogger.es',
  'ourgreatjogger.eu',  'ourgreatracoon.com', 'ourgreatracoon.net',
  'ourgreatracoon.es',  'ourgreatracoon.eu',  'ourgreatpued.es',
  'ourgreatpued.es',    'ourgreatpued.es',    'ourgreatpued.es',
  'ourbigjogger.com',   'ourbigjogger.net',   'ourbigjogger.es',
  'ourbigjogger.eu',    'ourbigracoon.com',   'ourbigracoon.net',
  'ourbigracoon.es',    'ourbigracoon.eu',    'ourbigpued.es',
  'ourbigpued.es',      'ourbigpued.es',      'ourbigpued.es'
]
````

Fíjate en los casos que incluyen la palabra puedes.

Por otro lado, recomendaría otra aproximación al problema del hack. Date cuenta de que ahora mismo depende de un if. Si necesitas incluir un nuevo dominio tienes que refactorizar tu código, incluyendo algo así como otro (ejemplo):

````
if (wordSlice[0].slice(-2) === "online") {
    return wordSlice[0].slice(0, -2) + ".online";
````

Intenta buscar una solución que no requiera refactorizar cada vez que cambie la lista de dominios

**Comment by AlvaroMartinFernandez** [comment]
Ya solucione el problema para que no se repita y salga el hack solo para la extension correspondiente, por otro lado solucione también el problema para no tener que refactorizar el codigo.

Un saludo

**Comment by agarzon48** [comment]
Grande!
